name: Publish

on:
   release:
      types: [published]
   workflow_dispatch:

jobs:
   publish-to-crates:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v3

         - name: Publish
           uses: katyo/publish-crates@v2
           with:
              registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
              dry-run: ${{ inputs.plan == 'dry-run' }}

   publish-to-aur:
      runs-on: ubuntu-latest
      steps:
         # Get the latest release info
         - name: Get latest release
           id: latest
           uses: pozetroninc/github-action-get-latest-release@v0.7.0
           with:
              owner: artrixdotdev
              repo: browsermux

         # Download PKGBUILD asset attached to the release
         - name: Download PKGBUILD artifact
           uses: robinraju/release-downloader@v1.9
           with:
              repository: artrixdotdev/browsermux
              tag: ${{ steps.latest.outputs.release }}
              fileName: "PKGBUILD"

         - name: Publish AUR package
           uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
           with:
              pkgname: browsermux
              pkgbuild: ./PKGBUILD
              commit_username: GitHub Action
              commit_email: actions@github.com
              ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
              commit_message: Update AUR package to ${{ steps.latest.outputs.release }}
              ssh_keyscan_types: rsa,ecdsa,ed25519
